apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dp2.name }}
  labels:
    app: {{ .Values.svc2.name }}
spec:
  replicas: {{ .Values.dp2.replicas }}
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: {{ .Values.dp2.image}}:{{ .Values.dp2.tag }}
        ports:
        - containerPort: {{ .Values.dp2.cPort }}
