apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc2.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.svc2.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.svc2.port }}
      targetPort: {{ .Values.svc2.tPort }}
