apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.svc.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.svc.port }}
      targetPort: {{ .Values.svc.tPort }}
